export const S = {
  appName: 'Harady',
  tagline: 'Гульня ў гарады',

  yourName: 'Тваё імя',
  namePlaceholder: 'Напрыклад, Алесь',
  createRoom: 'Стварыць пакой',
  joinRoom: 'Далучыцца',
  roomCode: 'Код пакоя',
  roomCodePlaceholder: 'ABC123',
  or: 'або',
  invalidCode: 'Няправільны код пакоя',
  nameRequired: 'Увядзі імя',

  players: 'Гульцы',
  you: 'ты',
  host: 'гаспадар',
  bot: 'бот',
  out: 'выбыў',
  missed: 'промахаў',
  passedTurn: (nick: string, n: number, max: number) => `${nick} прапусціў ход (${n}/${max})`,
  addBot: 'Дадаць бота',
  start: 'Пачаць',
  waiting: 'Чакаем гаспадара…',
  needPlayers: (n: number) => `Патрэбна хаця б ${n} гульні`,
  copyLink: 'Скапіраваць спасылку',
  copied: 'Скапіравана!',
  shareHint: 'Падзяліся спасылкай з сябрамі',

  // game
  chain: 'Ланцуг гарадоў',
  firstMove: 'Першы горад — любы',
  nextLetter: 'Наступны горад на літару',
  yourTurn: 'Твой ход!',
  turnOf: (n: string) => `Ход ${n}`,
  waitTurn: 'Чакаем іншага гульца…',
  youAreOut: 'Ты выбыў. Назірай за гульнёй.',
  nameCity: 'Назваць горад',
  placeholder: 'Назва горада…',
  pass: 'Здаюся',
  send: 'Даслаць',
  endGame: 'Скончыць гульню',
  endGameConfirm: 'Скончыць гульню для ўсіх?',

  // rejection reasons
  r_wrong_letter: (l: string) => `Патрэбна літара «${l}»`,
  r_already_used: 'Гэты горад ужо называлі',
  r_not_in_db: 'Такога горада няма ў базе',
  r_empty: 'Пуста',

  // end
  gameOver: 'Гульня скончана',
  winner: 'Пераможца',
  noWinner: 'Нічыя',
  noWinnerHint: 'Усе выбылі',
  scoreboard: 'Гульцы',
  chainLength: 'Даўжыня ланцуга',
  playAgain: 'Гуляць зноў',
  backHome: 'На галоўную',

  connecting: 'Злучэнне…',
  reconnecting: 'Перападключэнне…',
  roomNotFound: 'Пакой не знойдзены',
  connectionFailed: 'Не ўдалося падключыцца да сервера',
  leaveRoom: 'Выйсці',

  genericError: 'Нешта пайшло не так',
} as const
